insert into entries (participant_id, competition_id) values (1, 3);
insert into entries (participant_id, competition_id) values (2, 3);
insert into entries (participant_id, competition_id) values (3, 2);
insert into entries (participant_id, competition_id) values (4, 1);
insert into entries (participant_id, competition_id) values (5, 3);
-- insert into entries (participant_id, competition_id) values (6, 3);
-- insert into entries (participant_id, competition_id) values (7, 3);
-- insert into entries (participant_id, competition_id) values (8, 3);
insert into entries (participant_id, competition_id) values (9, 1);
insert into entries (participant_id, competition_id) values (10, 1);
-- insert into entries (participant_id, competition_id) values (11, 1);
insert into entries (participant_id, competition_id) values (12, 2);
-- insert into entries (participant_id, competition_id) values (13, 1);
-- insert into entries (participant_id, competition_id) values (14, 3);
-- insert into entries (participant_id, competition_id) values (15, 3);
-- insert into entries (participant_id, competition_id) values (16, 3);
-- insert into entries (participant_id, competition_id) values (17, 3);
-- insert into entries (participant_id, competition_id) values (18, 1);
insert into entries (participant_id, competition_id) values (19, 2);
-- insert into entries (participant_id, competition_id) values (20, 3);
-- insert into entries (participant_id, competition_id) values (21, 1);
-- insert into entries (participant_id, competition_id) values (22, 3);
-- insert into entries (participant_id, competition_id) values (23, 3);
-- insert into entries (participant_id, competition_id) values (24, 2);
-- insert into entries (participant_id, competition_id) values (25, 2);
-- insert into entries (participant_id, competition_id) values (26, 1);
-- insert into entries (participant_id, competition_id) values (27, 3);
-- insert into entries (participant_id, competition_id) values (28, 1);
-- insert into entries (participant_id, competition_id) values (29, 3);
-- insert into entries (participant_id, competition_id) values (30, 3);
-- insert into entries (participant_id, competition_id) values (31, 1);
-- insert into entries (participant_id, competition_id) values (32, 2);
-- insert into entries (participant_id, competition_id) values (33, 3);
-- insert into entries (participant_id, competition_id) values (34, 2);
-- insert into entries (participant_id, competition_id) values (35, 3);
-- insert into entries (participant_id, competition_id) values (36, 1);
-- insert into entries (participant_id, competition_id) values (37, 2);
-- insert into entries (participant_id, competition_id) values (38, 2);
-- insert into entries (participant_id, competition_id) values (39, 3);
-- insert into entries (participant_id, competition_id) values (40, 3);
