DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS scoring_systems CASCADE;
DROP TABLE IF EXISTS judges CASCADE;
DROP TABLE IF EXISTS participants CASCADE;
DROP TABLE IF EXISTS competitions CASCADE;
DROP TABLE IF EXISTS entries CASCADE;
DROP TABLE IF EXISTS scores CASCADE;




